Remove unused global variable [test_resowner]
src/test/modules/test_resowner/test_resowner_many.c:49:29: error: variable 'current_release_phase' set but not used [-Werror,-Wunused-but-set-global]

This was apparently never used (initial commit b8bff07daa8).

Discussion: https://www.postgresql.org/message-id/flat/eb013f9d-2247-444e-8815-9d17b4ce78e7%40eisentraut.org