Remove unused global variable [pg_dump]
src/bin/pg_dump/pg_dump_sort.c:160:15: error: variable 'preDataBoundId' set but not used [-Werror,-Wunused-but-set-global]

This was apparently never used (initial commit a1ef01fe163).

Discussion: https://www.postgresql.org/message-id/flat/eb013f9d-2247-444e-8815-9d17b4ce78e7%40eisentraut.org